### ISSUE TITLE
add new field recolectado to campo model

### ISSUE THREAD

**Issue by Japoivvb** [Samixanxo/Hibernate#4]
1. add recolectado attribute to campo model, it sets false and change true after vendimia

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb(in 3rd person) +  details 

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

**Comment by Samixanxo** [comment]
To add a new "Recolectado" field in the table we can do it through the model in the Hibernate application. On execution time it will create this new column at our DB. 

<img width="296" alt="image" src="https://github.com/Samixanxo/Hibernate/assets/114580765/6b8f7be6-632a-4976-89ad-a2b1a40be9a3">


<img width="177" alt="image" src="https://github.com/Samixanxo/Hibernate/assets/114580765/c95ca801-04a5-4d8f-bf43-29657651f132">

**Comment by Japoivvb** [comment]
> To add a new "Recolectado" field in the table we can do it through the model in the Hibernate application. On execution time it will create this new column at our DB. We also need to implement a method that will be in charge of setting it's value at true when vendimia is done.
> 
> <img alt="image" width="296" src="https://private-user-images.githubusercontent.com/114580765/313778012-6b8f7be6-632a-4976-89ad-a2b1a40be9a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODQwNjMsIm5iZiI6MTcxMjQ4Mzc2MywicGF0aCI6Ii8xMTQ1ODA3NjUvMzEzNzc4MDEyLTZiOGY3YmU2LTYzMmEtNDk3Ni04OWFkLWEyYjFhNDBiZTlhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDViYWIxMTY5MTdkODVjMjFlZTk2YmI0YzliM2MyMzNkOTk5OTNhM2ExNzY2MzFlNjBmZWZmZjg3ZTg5YjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gZaOe8PIug1PbvmmfvenRils1ZuYdpXlsV870yBhxXo"> <img alt="image" width="177" src="https://private-user-images.githubusercontent.com/114580765/313778389-c95ca801-04a5-4d8f-bf43-29657651f132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODQwNjMsIm5iZiI6MTcxMjQ4Mzc2MywicGF0aCI6Ii8xMTQ1ODA3NjUvMzEzNzc4Mzg5LWM5NWNhODAxLTA0YTUtNGQ4Zi1iZjQzLTI5NjU3NjUxZjEzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTE3ZTMxMmE2ZDJkMjg4NzZjZWYxZThhNmMxNDhmZGU4OWE0Y2Y2MjY2M2UzZDEyMmVkZjZkYWZkNDI3NzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ra57odI0aVoNgs3-vLjNuu1aZN9xVUW_keiWA6UyTC4"> <img alt="image" width="211" src="https://private-user-images.githubusercontent.com/114580765/313784765-f4faca9d-962c-4394-8bd7-6cefeae50437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODQwNjMsIm5iZiI6MTcxMjQ4Mzc2MywicGF0aCI6Ii8xMTQ1ODA3NjUvMzEzNzg0NzY1LWY0ZmFjYTlkLTk2MmMtNDM5NC04YmQ3LTZjZWZlYWU1MDQzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODEwMWE0ZTBiY2ZhOTgyNmEyMzg1NGZlYzUzZjQzNGZjZjMwNzBhNWQ4YTlmODY0NzIzNGM1ZTczNTAxM2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XRLtg2ZwHgRzVaS5CtNMcQtW3ZZdc-qgINndMV-7zt8"> <img alt="image" width="342" src="https://private-user-images.githubusercontent.com/114580765/313784852-9c699b7d-06fa-49cf-a45f-96be3d45ecbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODQwNjMsIm5iZiI6MTcxMjQ4Mzc2MywicGF0aCI6Ii8xMTQ1ODA3NjUvMzEzNzg0ODUyLTljNjk5YjdkLTA2ZmEtNDljZi1hNDVmLTk2YmUzZDQ1ZWNiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTc4NWNmZjgzZTA4NDM5NTBmYTBmZTQwMjNkOWM0MmM0ZWY4YjI1ZDkzZDBkMzRhMzFlNmY2NTAzYTFjY2M2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qO5MDj0ASvR_dAFwbTLjubKREGcx7T31MuCJfrdDX04"> <img alt="image" width="193" src="https://private-user-images.githubusercontent.com/114580765/313788349-376b27bc-408b-4a12-a5ef-9d06671c85f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODQwNjMsIm5iZiI6MTcxMjQ4Mzc2MywicGF0aCI6Ii8xMTQ1ODA3NjUvMzEzNzg4MzQ5LTM3NmIyN2JjLTQwOGItNGExMi1hNWVmLTlkMDY2NzFjODVmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTU2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2U1ZjQ3YjI2MjA5NjJkMDUxMDZjZWNkNjA0NWMyM2ZkNjZjOTc4NjRhMWVjNmNlY2E4Y2IwZmYwYzg5M2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tn6pqtl5Q6fjp7PYsUtPMlsjULSVZ-kp6ww9cNoNZ_4">

better if you use the corresponding setRecolectado

**Comment by Japoivvb** [comment]
1. ok
2. ko
3. ok
4. ok
5. ok
